package com.gilead.medicalinventory.domain;

import static com.gilead.medicalinventory.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MedicineAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineAllPropertiesEquals(Medicine expected, Medicine actual) {
        assertMedicineAutoGeneratedPropertiesEquals(expected, actual);
        assertMedicineAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineAllUpdatablePropertiesEquals(Medicine expected, Medicine actual) {
        assertMedicineUpdatableFieldsEquals(expected, actual);
        assertMedicineUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineAutoGeneratedPropertiesEquals(Medicine expected, Medicine actual) {
        assertThat(actual)
            .as("Verify Medicine auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineUpdatableFieldsEquals(Medicine expected, Medicine actual) {
        assertThat(actual)
            .as("Verify Medicine relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getGenericName()).as("check genericName").isEqualTo(expected.getGenericName()))
            .satisfies(a -> assertThat(a.getDosageForm()).as("check dosageForm").isEqualTo(expected.getDosageForm()))
            .satisfies(a -> assertThat(a.getStrength()).as("check strength").isEqualTo(expected.getStrength()))
            .satisfies(a ->
                assertThat(a.getUnitPrice()).as("check unitPrice").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getUnitPrice())
            )
            .satisfies(a -> assertThat(a.getReorderLevel()).as("check reorderLevel").isEqualTo(expected.getReorderLevel()))
            .satisfies(a ->
                assertThat(a.getControlledSubstance()).as("check controlledSubstance").isEqualTo(expected.getControlledSubstance())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMedicineUpdatableRelationshipsEquals(Medicine expected, Medicine actual) {
        assertThat(actual)
            .as("Verify Medicine relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()))
            .satisfies(a -> assertThat(a.getSupplier()).as("check supplier").isEqualTo(expected.getSupplier()));
    }
}
