package com.gilead.medicalinventory.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockLotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockLotAllPropertiesEquals(StockLot expected, StockLot actual) {
        assertStockLotAutoGeneratedPropertiesEquals(expected, actual);
        assertStockLotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockLotAllUpdatablePropertiesEquals(StockLot expected, StockLot actual) {
        assertStockLotUpdatableFieldsEquals(expected, actual);
        assertStockLotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockLotAutoGeneratedPropertiesEquals(StockLot expected, StockLot actual) {
        assertThat(actual)
            .as("Verify StockLot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockLotUpdatableFieldsEquals(StockLot expected, StockLot actual) {
        assertThat(actual)
            .as("Verify StockLot relevant properties")
            .satisfies(a -> assertThat(a.getBatchNumber()).as("check batchNumber").isEqualTo(expected.getBatchNumber()))
            .satisfies(a -> assertThat(a.getExpiryDate()).as("check expiryDate").isEqualTo(expected.getExpiryDate()))
            .satisfies(a -> assertThat(a.getQuantityOnHand()).as("check quantityOnHand").isEqualTo(expected.getQuantityOnHand()))
            .satisfies(a -> assertThat(a.getReceivedDate()).as("check receivedDate").isEqualTo(expected.getReceivedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockLotUpdatableRelationshipsEquals(StockLot expected, StockLot actual) {
        assertThat(actual)
            .as("Verify StockLot relationships")
            .satisfies(a -> assertThat(a.getMedicine()).as("check medicine").isEqualTo(expected.getMedicine()))
            .satisfies(a -> assertThat(a.getStorageLocation()).as("check storageLocation").isEqualTo(expected.getStorageLocation()));
    }
}
