package com.gilead.medicalinventory.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StorageLocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageLocationAllPropertiesEquals(StorageLocation expected, StorageLocation actual) {
        assertStorageLocationAutoGeneratedPropertiesEquals(expected, actual);
        assertStorageLocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageLocationAllUpdatablePropertiesEquals(StorageLocation expected, StorageLocation actual) {
        assertStorageLocationUpdatableFieldsEquals(expected, actual);
        assertStorageLocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageLocationAutoGeneratedPropertiesEquals(StorageLocation expected, StorageLocation actual) {
        assertThat(actual)
            .as("Verify StorageLocation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageLocationUpdatableFieldsEquals(StorageLocation expected, StorageLocation actual) {
        assertThat(actual)
            .as("Verify StorageLocation relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getBuilding()).as("check building").isEqualTo(expected.getBuilding()))
            .satisfies(a ->
                assertThat(a.getTemperatureControlled()).as("check temperatureControlled").isEqualTo(expected.getTemperatureControlled())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStorageLocationUpdatableRelationshipsEquals(StorageLocation expected, StorageLocation actual) {
        // empty method
    }
}
