# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: YjU5NmYxODkzMjM4MzExZWFlZTMyMGU5ZGFjZjViMzZmYWUzZGYxZTBlZjBiNTk1YmUzMDdhOGVlNjYxYTlkZTk4M2ViMzU2ODBhYjc5NzExZTM3MjZiZDg1Y2Q0Nzg2MTBkOWNlMzEzZGM3MGNiNGE5NGJiNjM1ZTc1YTE5M2U=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: medicalinventory
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: medicalinventory
    password:
